# Change these first
owner: TrizaCorporation # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: T:Riza
    url: https://www.triza.dev
    maxResponseTime: 1000
  - name: T:Riza Api
    url: https://infra.triza.dev/api
    maxResponseTime: 1000
  - name: T:Riza Docs
    url: https://docs.triza.dev
    maxResponseTime: 1000
  - name: T:Riza Community Forum
    url: https://community.triza.dev
    maxResponseTime: 1000
  - name: T:Riza Roblox Proxy
    url: https://rprxy.triza.dev
    maxResponseTime: 1000
  - name: RbxVeri
    url: https://verify.triza.dev
    maxResponseTime: 1000
  - name: Melody
    url: https://melody.triza.dev
    maxResponseTime: 1000
  - name: Roblox
    url: https://www.roblox.com
    maxResponseTime: 1000
  - name: Roblox Group Api
    url: https://groups.roblox.com
    maxResponseTime: 1000
  - name: Roblox TextFilter Api
    url: https://textfilter.roblox.com
    maxResponseTime: 1000
  - name: Roblox DataStore Api
    url: https://gamepersistence.roblox.com
    maxResponseTime: 1000
  - name: Cloudflare
    url: https://www.cloudflare.com
    maxResponseTime: 1000
  - name: Discord
    url: https://discord.com
    maxResponseTime: 1000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: old.status.triza.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/TrizaCorporation/Status/master/trizastatuslogo.png
  name: T:Riza Status
  introTitle: "Status Page for Tracking all Incidents which relate to T:Riza"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/TrizaCorporation/Status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Forum
      href: https://community.triza.dev
  theme: dark
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/40 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
